server.port=8081

# PostgreSQL configuration
spring.datasource.url=jdbc:postgresql://postgresql_container:5432/challenge
spring.datasource.username=myuser
spring.datasource.password=mypassword
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# MinIO configuration (default values can be overridden by environment variables)
minio.url=${MINIO_URL:http://localhost:9000}
minio.accessKey=${MINIO_ACCESS_KEY:minioadmin}
minio.secretKey=${MINIO_SECRET_KEY:minioadminpassword}
minio.bucketName=${MINIO_BUCKET_NAME:document-bucket}